name: pnet_env
channels:
  - defaults
  - plotly
dependencies:
  - imageio=2.6.1
  - enum34=1.1.6
  - futures=3.3.0
  - pandas=0.23.4
  - yaml=0.1.7
  - markdown=3.1.1
  - scipy=1.1.0
  - hdf5=1.10.4
  - keras-preprocessing=1.1.0
  - tensorboard=1.12.2
  - scikit-learn=0.20.1
  - keras-applications=1.0.8
  - subprocess32=3.5.4
  - plotly=4.5.4
  - keras-base=2.2.4
  - numpy=1.16.6
  - protobuf=3.11.2
  - pip=18.1
  - pyyaml=5.1.1
  - scikit-image=0.14.2
  - h5py=2.9.0
  - python=2.7.15
  - tensorflow=1.12.0
  - keras=2.2.4
  - plotly-orca=1.3.1
  - decorator=4.4.2
  - pip:
    - gdown==4.7.1
